### ISSUE TITLE
Qemu semihosting Memory configuration

### ISSUE THREAD

**Issue by AbhijitInamdar5** [xpack/arm-linux-files#1]
Hi, I'm using qemu-4.2.0 on Ubuntu-16.04 and  4.15.0-142-generic #146~16.04.1-Ubuntu SMP .... x86_64 x86_64 x86_64 GNU/Linux.
The startup and linker are from https://github.com/ARM-software/CMSIS/tree/master/Device/ARM/ARMCM3/Source/GCC. I'm using the .S and .ld scripts from the above link. 

To what memory configurations should I change such that qemu -semihosting is correctly done.

Thank you.

**Comment by ilg-ul** [comment]
Sorry, but I don't know the configuration details of the current QEMU. Personally I don't think that semihosting expects a specific memory map, it uses only a specific BKPT instructions to communicate with the debugger.
